### ISSUE TITLE
Confused about the input genotype format

### ISSUE THREAD

**Issue by QianXiaobo** [tyjo/dystruct#11]
Hi tyjo,

I notice that "Input genotype matrix is now a standard format (EIGENSTRAT .geno)" and you mentioned that "The genotype matrix is a SNPs by individual matrix where each entry encodes **the number of non-reference alleles** (i.e. 0, 1, 2) for that genotype with no spaces between entries. ". However, **the meanning of 0,1,2 in EIGENSTRATE .geno file described from DReichLab is the count of reference alleles** (showed at the bottom).  I am not sure which explanation is correct.

![image](https://user-images.githubusercontent.com/40785771/147315167-35d148d9-3de3-4602-8cf8-54bfff7859e0.png)
https://github.com/DReichLab/EIG/tree/master/CONVERTF

Best wishes, 
Xb

**Comment by tyjo** [comment]
Good catch. Fortunately, for dystruct it doesn't matter if the genotype matrix counts reference or non-reference alleles. The only difference is that estimated allele frequencies will be flipped from p to 1 - p.

**Comment by QianXiaobo** [comment]
Got it. Thank you very much!
