### ISSUE TITLE
Ambiguous column headers

### ISSUE THREAD

**Issue by geneanalyst** [tyjo/dystruct#3]
Please clarify. Should oldest sample be assigned time 0 in column header?

Also, what is the recommended minimum number of samples per population. Is it 1?

**Comment by tyjo** [comment]
Yes, the oldest sample should have time 0 in the column header.

The answer to your second question: it depends. If your samples have a lot of missing genotypes, then you'll need more than one sample per population to cover all of the loci in the remaining populations. In simulations we were able to identify populations with one example from an ancient population, but appear in the mixture components for modern populations.
