### ISSUE TITLE
Modern and ancient samples in the same dataset.

### ISSUE THREAD

**Issue by francescomontinaro** [tyjo/dystruct#8]
Hi,

I am experimenting with dystruct using a dataset contating modern and ancient samples. Would you suggest to make all the modern as pseudo-haploid?

What would you say would be the best way to deal with it?

Thank you!

**Comment by tyjo** [comment]
DyStruct can handle both pseudo-haploid and diploid samples together. It automatically detects pseudo-haploid samples and treats them appropriately. There is no need to make the modern samples pseudo-haploid.

**Comment by francescomontinaro** [comment]
Great, Thank you!
