### ISSUE TITLE
sample_times

### ISSUE THREAD

**Issue by josephresearcher** [tyjo/dystruct#9]
Hello
The software is great
I worked on your samples
But when I wanted to work with my files, I had a problem
generation-times FILE
Please explain more about "sample_times" file
How to get it from ordinary data? 
Thank You

**Comment by tyjo** [comment]
Ancient DNA samples typically have accompanying carbon date estimates that you can use to compute sample times. Years are converted to generation times by assuming a 25-year generation time for humans. Then, generation times are grouped together using the script `bin_sample_times.py`. The steps are:

1. Record a carbon date estimate in years for each sample. Only the relative order between dates matters. You can set your earliest sample to 0, then count from there.
2. Convert carbon dates to generation time. In the paper, we assumed a 25 year generation time. Divide carbon date estimates by generation time to convert years to generations.
3. Group nearby generation times together. The script `bin_sample_times.py` should do this for you. The total number of time points affects run time, so you want this to be small if possible.

The output of step 3 gives the generation times expected by DyStruct.

**Comment by josephresearcher** [comment]
thank you very much
Can we run the software without "sample times"?
If it runs without "sample times", is there a problem with the results?

**Comment by tyjo** [comment]
Without sample times you are better off using ADMIXTURE: https://dalexander.github.io/admixture/download.html

**Comment by josephresearcher** [comment]
Thanks again
Your software is more accurate
So I try to generate "Sample time"
